name: Diff Checker

on: [pull_request]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_DIFF_THRESHOLD: 400

jobs:
  setup:
    if: contains(github.event.pull_request.labels.*.name, 'ignore diff') == false
    runs-on: ubuntu-latest
    steps:
      - name: Diff check
        uses: actions/github-script@v7
        with:
          retries: 3
          retry-exempt-status-codes: 400,401,500
          script: |
            const { data } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const prDiff = data.additions + data.deletions;

            if (prDiff > process.env.PR_DIFF_THRESHOLD) {
              throw new Error(`This PR is too big! Please keep it under ${process.env.PR_DIFF_THRESHOLD} changes.`);
            }
