name: Actions

run-name: Created by ${{ github.actor }}

on: [push]

jobs:
  tsc:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: install packages
        run: pnpm install --frozen-lockfile
      - name: type check
        run: pnpm tsc --noEmit

  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: install packages
        run: pnpm install --frozen-lockfile
      - name: eslint
        run: pnpm eslint --config eslint.config.js .
        env:
          ESLINT_USE_FLAT_CONFIG: true

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: install packages
        run: pnpm install --frozen-lockfile
      - name: test
        run: pnpm vitest run --config ./vite.config.ts

  cspell:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: install packages
        run: pnpm install --frozen-lockfile
      - name: spell check
        run: pnpm cspell "**"
